// グローバル CSS（アニメーション等）を一度だけ挿入する
if (typeof document !== "undefined") {
  const styleId = "shogi-trainer-global-styles";
  if (!document.getElementById(styleId)) {
    const el = document.createElement("style");
    el.id = styleId;
    el.textContent = `@keyframes spin { to { transform: rotate(360deg) } }`;
    document.head.appendChild(el);
  }
}

export const s = {
  // ── レイアウト ──
  root: {
    minHeight: "100vh",
    background: "#0e0e0e",
    color: "#f0e6d3",
    fontFamily: "'Noto Serif JP','Georgia',serif",
    position: "relative",
  },
  bgGrid: {
    position: "fixed",
    inset: 0,
    pointerEvents: "none",
    zIndex: 0,
    backgroundImage: `
      radial-gradient(ellipse at 15% 15%, rgba(192,57,43,0.13) 0%, transparent 55%),
      radial-gradient(ellipse at 85% 85%, rgba(41,128,185,0.09) 0%, transparent 55%),
      repeating-linear-gradient(0deg,transparent,transparent 64px,rgba(255,255,255,0.018) 64px,rgba(255,255,255,0.018) 65px),
      repeating-linear-gradient(90deg,transparent,transparent 64px,rgba(255,255,255,0.018) 64px,rgba(255,255,255,0.018) 65px)
    `,
  },
  header: {
    position: "relative",
    zIndex: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "13px 20px",
    borderBottom: "1px solid rgba(192,57,43,0.25)",
    background: "rgba(14,14,14,0.85)",
    backdropFilter: "blur(12px)",
  },
  logo: { fontSize: 18, fontWeight: 700, letterSpacing: "0.18em", color: "#c0392b" },
  statChip: {
    fontSize: 12,
    color: "#aaa",
    background: "rgba(255,255,255,0.06)",
    padding: "3px 12px",
    borderRadius: 20,
  },
  main: {
    position: "relative",
    zIndex: 10,
    maxWidth: 640,
    margin: "0 auto",
    padding: "24px 16px 60px",
  },

  // ── ホーム ──
  section: { display: "flex", flexDirection: "column", gap: 20 },
  heroLabel: {
    fontSize: 11,
    letterSpacing: "0.3em",
    color: "#c0392b",
    textAlign: "center",
    paddingTop: 8,
  },
  heroTitle: { fontSize: 28, fontWeight: 700, lineHeight: 1.35, textAlign: "center", margin: 0 },
  settingsBar: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.09)",
    borderRadius: 12,
    padding: "14px 16px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  settingGroup: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  settingLabel: { fontSize: 11, color: "#888", letterSpacing: "0.1em", minWidth: 68 },
  pillRow: { display: "flex", gap: 6 },
  pill: {
    fontSize: 12,
    padding: "4px 14px",
    borderRadius: 20,
    border: "1px solid rgba(255,255,255,0.18)",
    background: "transparent",
    color: "#ccc",
    cursor: "pointer",
    letterSpacing: "0.05em",
  },
  select: {
    background: "rgba(255,255,255,0.07)",
    border: "1px solid rgba(255,255,255,0.15)",
    borderRadius: 8,
    color: "#f0e6d3",
    fontSize: 13,
    padding: "4px 10px",
    fontFamily: "'Noto Serif JP','Georgia',serif",
  },

  // ── カテゴリリスト ──
  catList: { display: "flex", flexDirection: "column", gap: 8 },
  catRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderLeft: "3px solid",
    borderRadius: 10,
    padding: "12px 14px",
    cursor: "pointer",
    textAlign: "left",
  },
  catRowIcon: { fontSize: 20, minWidth: 28 },
  catRowText: { flex: 1 },
  catRowName: { fontSize: 14, fontWeight: 600, color: "#f0e6d3", letterSpacing: "0.05em" },
  catRowDesc: { fontSize: 11, color: "#888", marginTop: 2 },

  // ── クイズカード ──
  quizCard: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 14,
    padding: "22px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  quizTop: { display: "flex", alignItems: "center", gap: 8 },
  badge: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.08em",
    padding: "3px 10px",
    borderRadius: 20,
    color: "#fff",
  },
  diffPill: {
    fontSize: 11,
    fontWeight: 600,
    padding: "3px 10px",
    borderRadius: 20,
    color: "#fff",
  },
  qBox: {
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 9,
    padding: "14px 16px",
  },
  qLabel: { fontSize: 10, letterSpacing: "0.25em", color: "#c0392b", margin: "0 0 7px" },
  qText: { fontSize: 14, lineHeight: 1.75, color: "#f0e6d3", margin: 0 },
  hintBtn: {
    alignSelf: "flex-start",
    background: "transparent",
    border: "1px dashed rgba(255,255,255,0.2)",
    color: "#999",
    fontSize: 12,
    padding: "6px 14px",
    borderRadius: 7,
    cursor: "pointer",
  },
  hintBox: {
    background: "rgba(255,220,0,0.07)",
    border: "1px solid rgba(255,220,0,0.18)",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 13,
    color: "#f0e6d3",
    lineHeight: 1.65,
  },
  textarea: {
    background: "rgba(255,255,255,0.07)",
    border: "1px solid rgba(255,255,255,0.14)",
    borderRadius: 9,
    padding: "11px 13px",
    color: "#f0e6d3",
    fontSize: 14,
    lineHeight: 1.65,
    resize: "vertical",
    fontFamily: "'Noto Serif JP','Georgia',serif",
    outline: "none",
  },
  btnRow: { display: "flex", gap: 8, justifyContent: "space-between" },
  ghostBtn: {
    background: "transparent",
    border: "1px solid rgba(255,255,255,0.14)",
    color: "#aaa",
    fontSize: 13,
    padding: "9px 16px",
    borderRadius: 8,
    cursor: "pointer",
  },
  redBtn: {
    background: "linear-gradient(135deg,#c0392b,#922b21)",
    border: "none",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    padding: "9px 22px",
    borderRadius: 8,
    cursor: "pointer",
    letterSpacing: "0.08em",
  },
  revealBtn: {
    background: "transparent",
    border: "none",
    color: "#666",
    fontSize: 12,
    cursor: "pointer",
    textDecoration: "underline",
  },
  revealBox: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.09)",
    borderRadius: 8,
    padding: "12px 14px",
    fontSize: 13,
    color: "#ccc",
    lineHeight: 1.7,
    textAlign: "left",
  },

  // ── 結果 ──
  correctBanner: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    border: "1px solid",
    borderRadius: 10,
    padding: "14px 18px",
  },
  scoreMsg: {
    fontSize: 15,
    color: "#f0e6d3",
    textAlign: "center",
    letterSpacing: "0.05em",
    padding: "4px 0",
  },

  // ── フィードバック ──
  feedRow: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 9,
    padding: "12px 14px",
  },
  feedTag: {
    display: "inline-block",
    fontSize: 10,
    fontWeight: 600,
    color: "#fff",
    padding: "2px 9px",
    borderRadius: 10,
    marginBottom: 7,
    letterSpacing: "0.05em",
  },
  feedText: { fontSize: 13, color: "#ddd", lineHeight: 1.7, margin: 0 },
  modelBox: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 9,
    padding: "12px 14px",
  },
  modelRows: { display: "flex", flexDirection: "column", gap: 10, marginTop: 8 },
  modelRow: { display: "flex", alignItems: "flex-start", gap: 10 },
  modelIcon: { fontSize: 15, minWidth: 20, paddingTop: 1 },
  modelRight: { display: "flex", flexDirection: "column", gap: 2 },
  modelLabel: { fontSize: 10, color: "#888", letterSpacing: "0.1em" },
  modelValue: { fontSize: 13, color: "#f0e6d3", lineHeight: 1.65 },

  // ── スピナー / エラー ──
  spinWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 14,
    padding: "36px 0",
  },
  spinner: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    border: "3px solid rgba(255,255,255,0.1)",
    borderTop: "3px solid #c0392b",
    animation: "spin 0.75s linear infinite",
  },
  spinText: { color: "#888", fontSize: 13, letterSpacing: "0.1em" },
  errText: { color: "#c0392b", fontSize: 13, textAlign: "center" },

  // ── 4択 ──
  choicesGrid: { display: "flex", flexDirection: "column", gap: 8 },
  choiceBtn: {
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.15)",
    borderRadius: 9,
    padding: "11px 14px",
    color: "#f0e6d3",
    fontSize: 14,
    textAlign: "left",
    cursor: "pointer",
    lineHeight: 1.5,
    transition: "all 0.15s",
  },

  // ── 小話 ──
  kobanashiRow: { display: "flex", gap: 8 },
  kobanashiBtn: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid",
    borderRadius: 10,
    padding: "10px 8px",
    cursor: "pointer",
  },
  kobanashiIcon: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
  },
  kobanashiName: { fontSize: 12, color: "#f0e6d3", fontWeight: 600 },
  kobanashiRank: { fontSize: 12, fontWeight: 600 },

  // ── モーダル ──
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.7)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
    padding: 20,
  },
  modalCard: {
    background: "#1a1a1a",
    border: "1px solid",
    borderRadius: 16,
    padding: "24px 20px",
    maxWidth: 400,
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  modalHeader: { display: "flex", alignItems: "center", gap: 12 },
  modalIcon: {
    width: 44,
    height: 44,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 22,
    flexShrink: 0,
  },
  modalName: { fontSize: 16, fontWeight: 700, letterSpacing: "0.05em" },
  modalRole: { fontSize: 11, color: "#888" },
  modalText: { fontSize: 14, color: "#f0e6d3", lineHeight: 1.85, letterSpacing: "0.03em" },
  modalClose: {
    background: "rgba(255,255,255,0.07)",
    border: "1px solid rgba(255,255,255,0.15)",
    color: "#aaa",
    fontSize: 13,
    padding: "8px",
    borderRadius: 8,
    cursor: "pointer",
    alignSelf: "flex-end",
  },

  // ── 親密度バー ──
  affinityBar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid",
    borderRadius: 10,
    padding: "10px 14px",
  },
  affinityIcon: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
    flexShrink: 0,
  },
  affinityName: { fontSize: 13, color: "#f0e6d3", fontWeight: 600, flex: 1 },
  affinityDelta: { fontSize: 15, fontWeight: 700 },
  affinityVal: { fontSize: 12, color: "#888" },

  // ── キャラクターバッジ ──
  charBadge: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "rgba(255,255,255,0.05)",
    border: "1px solid",
    borderRadius: 10,
    padding: "10px 14px",
    marginBottom: 2,
  },
  charIcon: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
    flexShrink: 0,
  },
  charInfo: { display: "flex", flexDirection: "column", gap: 1, flex: 1 },
  charName: { fontSize: 14, fontWeight: 700, letterSpacing: "0.05em" },
  charRole: { fontSize: 10, color: "#888", letterSpacing: "0.08em" },
  charLabel: { fontSize: 11, color: "#666", letterSpacing: "0.05em" },
};
